version: '3'

services:
  db:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8090:8090"
    links:
      - db:db
    depends_on:
      - db
