version: '3.1'
services:
  app:
    container_name: bookare
    image: bookare
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=456321
      - POSTGRES_DB=book_exchange