version: '3.1'

services:
  app:

    image: bookare
    build: ./
      context: .
    container_name: app
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=456321